name: Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main

  publish:
    needs: tag-and-release
    runs-on: ubuntu-latest
    # only run this job if the previous job created a new tag
    if: needs.tag-and-release.outputs.new_tag != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/maltekrupa/clamav-rest:latest, ghcr.io/maltekrupa/clamav-rest:${{needs.tag-and-release.outputs.new_tag}}
